package com.grateful.deadly.core.database.schema

import org.json.JSONObject
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.io.File

/**
 * Guards against schema drift between the prebuilt catalog seed contract
 * (`data/catalog_schema.json`) and the Room schema the app actually ships.
 *
 * The seed (`catalog.db`) is copied column-by-column into the live Room DB by
 * [com.grateful.deadly.core.database.service.SeedDatabaseImportService]. If a Room
 * catalog column is renamed/removed without updating the contract (or vice-versa),
 * that copy would fail at runtime on a user's first launch. This test catches it in
 * CI instead, by asserting every column the contract declares exists in Room's
 * exported schema, with matching primary keys.
 *
 * Reads Room's exported schema JSON (committed under `schemas/`, generated by the
 * `room.schemaLocation` KSP arg). If that file hasn't been generated yet (e.g. a
 * checkout that has never been built), the test is skipped with guidance rather than
 * failing spuriously — a real build regenerates it and the assertions run.
 */
class CatalogSeedSchemaDriftTest {

    private val catalogTables = listOf("shows", "recordings", "dead_collections", "data_version")

    @Test
    fun roomSchemaCoversCatalogSeedContract() {
        val contract = loadJson(findUp("data/catalog_schema.json"))
            ?: error("Could not locate data/catalog_schema.json from ${File("").absolutePath}")

        val roomSchemaFile = findRoomSchema()
        assumeTrue(
            "Room schema not exported yet — build the :core:database module once " +
                "(exportSchema=true + room.schemaLocation) and commit schemas/. Skipping drift check.",
            roomSchemaFile != null
        )
        val room = loadJson(roomSchemaFile!!)!!
        val roomEntities = room.getJSONObject("database").getJSONArray("entities")

        // tableName -> (columnNames, primaryKeyColumns)
        val roomByTable = HashMap<String, Pair<Set<String>, List<String>>>()
        for (i in 0 until roomEntities.length()) {
            val e = roomEntities.getJSONObject(i)
            val table = e.getString("tableName")
            val cols = e.getJSONArray("fields").let { fields ->
                (0 until fields.length()).map { fields.getJSONObject(it).getString("columnName") }.toSet()
            }
            val pk = e.optJSONObject("primaryKey")?.getJSONArray("columnNames")?.let { pkArr ->
                (0 until pkArr.length()).map { pkArr.getString(it) }
            } ?: emptyList()
            roomByTable[table] = cols to pk
        }

        val contractTables = contract.getJSONObject("tables")
        for (table in catalogTables) {
            val spec = contractTables.getJSONObject(table)
            val contractCols = spec.getJSONArray("columns").let { arr ->
                (0 until arr.length()).map { arr.getJSONObject(it).getString("name") }
            }
            val contractPk = spec.getJSONArray("primaryKey").let { arr ->
                (0 until arr.length()).map { arr.getString(it) }
            }

            val (roomCols, roomPk) = roomByTable[table]
                ?: error("Room schema is missing catalog table '$table'")

            val missing = contractCols.filterNot { it in roomCols }
            assertTrue(
                "Catalog seed columns absent from Room table '$table': $missing " +
                    "(Room has: ${roomCols.sorted()}). Update the entity or data/catalog_schema.json.",
                missing.isEmpty()
            )
            assertTrue(
                "Primary key mismatch for '$table': contract=$contractPk room=$roomPk",
                contractPk == roomPk
            )
        }
    }

    private fun loadJson(file: File?): JSONObject? =
        file?.takeIf { it.isFile }?.let { JSONObject(it.readText()) }

    /** Walk up from the working dir to find a repo-relative path (e.g. data/catalog_schema.json). */
    private fun findUp(relative: String): File? {
        var dir: File? = File("").absoluteFile
        while (dir != null) {
            val candidate = File(dir, relative)
            if (candidate.isFile) return candidate
            dir = dir.parentFile
        }
        return null
    }

    /** Newest exported Room schema under <module>/schemas/<db-class>/<version>.json. */
    private fun findRoomSchema(): File? {
        val schemasDir = sequenceOf(File("schemas"), File("androidApp/core/database/schemas"))
            .firstOrNull { it.isDirectory }
            ?: findUp("androidApp/core/database/schemas")?.takeIf { it.isDirectory }
            ?: return null
        return schemasDir.walkTopDown()
            .filter { it.isFile && it.extension == "json" }
            .maxByOrNull { it.nameWithoutExtension.toIntOrNull() ?: -1 }
    }
}
